### ISSUE TITLE
How to open text editor on ubuntu 20.04 ?

### ISSUE THREAD

**Issue by vivek80801** [Arsenic-ATG/text-editor#3]
How to open this text editor on ubuntu 20.04 ?

**Comment by Arsenic-ATG** [comment]
@vivek80801 this project is still under construction and is not reached to a point that it can be used by anyone. 

But here are the steps that you can follow to compile and 🏃‍♂️run this project to see its status (😅nothing much to see right now) :- 
1) Clone/Download the repo
2) Open terminal and navigate to the project directory
3) Compile the project using the `make` command (might generate some warnings as it is still under construction)
4) An executable(with name `editor`) would be created, run the **executable**  to use it.
 ----
Hope the instructions are clear, if you face any difficulty in following any of the above steps then feel free to ask it here.🙂

**P.S.** : I will update the [readme](https://github.com/Arsenic-ATG/text-editor/blob/master/README.md) of the project as soon as it becomes functional with all the necessary information.
