### ISSUE TITLE
Split the program across multiple files

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Text-Editor#5]
- Split the program across multiple files so that it becomes easier to work and debug. 
- update makefile to link the files together during building.

splitting is partially marked with comments in the main file.

**Comment by Ashborn-SM** [comment]
@Arsenic-ATG can you assign me to this issue?

**Comment by Arsenic-ATG** [comment]
## Update

Splitting of the source is being worked upon in [devel_muliple_file](https://github.com/Arsenic-ATG/Text-Editor/tree/devel_multiple_file) branch of the repository.

**Comment by Arsenic-ATG** [comment]
The source is now successfully split across multiple files.
